### ISSUE TITLE
ValueError: Error parsing asn1crypto.core.OctetString - method should have been primitive, but constructed was found     while parsing asn1crypto.cms.EncryptedContentInfo

### ISSUE THREAD

**Issue by birdie1** [bikram990/PyScep#17]
Hello,
I get the following error:

```
Traceback (most recent call last):
  File "./main.py", line 27, in <module>
    res = client.enrol(
          ^^^^^^^^^^^^^
  File "/home/jonas/.local/lib/python3.11/site-packages/scep/Client/client.py", line 123, in enrol
    return self._pki_operation(identity=identity, identity_private_key=identity_private_key, envelope=envelope, message_type=MessageType.PKCSReq, cacaps=cacaps, ca_certs=ca_certs, transaction_id=transaction_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonas/.local/lib/python3.11/site-packages/scep/Client/client.py", line 154, in _pki_operation
    decrypted_bytes = cert_rep.get_decrypted_envelope_data(identity, identity_private_key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonas/.local/lib/python3.11/site-packages/scep/Client/message.py", line 232, in get_decrypted_envelope_data
    encrypted_content_bytes = encrypted_contentinfo['encrypted_content'].native
                              ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asn1crypto/core.py", line 3536, in __getitem__
    raise e
  File "/usr/lib/python3.11/site-packages/asn1crypto/core.py", line 3531, in __getitem__
    return self._lazy_child(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asn1crypto/core.py", line 3478, in _lazy_child
    child = self.children[index] = _build(*child)
                                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asn1crypto/core.py", line 5555, in _build
    raise ValueError(unwrap(
ValueError: Error parsing asn1crypto.core.OctetString - method should have been primitive, but constructed was found
    while parsing asn1crypto.cms.EncryptedContentInfo
```
The SCEP provider send out the certificate, but it looks like PyScep is not able to parse it.

Any idea what I can change to get the certificate?

**Comment by pegahnikbakht** [comment]
any fix on this?

**Comment by bikram990** [comment]
@pegahnikbakht  and @birdie1  Could you please give little bit more details on how to reproduce it ?

**Comment by ajayajayan** [comment]
@bikram990 I got this issue when I tried to process the response with the sample request response headers mentioned below.
{'Transfer-Encoding': 'chunked', 'Content-Type': 'application/x-pki-message'}
could you please look on it?

**Comment by bikram990** [comment]
@ajayajayan could you please mention steps to reproduce? And give more details about your environment like which scep server you are using ?

**Comment by ajayajayan** [comment]
@bikram990 Hi, I'm using the PORTNOX SCEP server. When I tried it, I encountered an issue.
The issue occurred on this line:
encrypted_content_bytes = encrypted_contentinfo['encrypted_content'].native

**Comment by ajayajayan** [comment]
@bikram990 any updates? can you check it? its very urgent. that's why.

**Comment by bikram990** [comment]
@ajayajayan I do not have access to PORTNOX scep server. Could you please either provide me access to one or dump the network request and share?

**Comment by FilippVolodin** [comment]
The problem occurs in asn1crypto due to non-standard encoding  (for CMS protocol) of `encrypted_content` by SCEP server (details: https://github.com/wbond/asn1crypto/issues/36). For my needs, I modified the `get_decrypted_envelope_data` method in `message.py` as workaround:

```python
        # before
        # encrypted_content_bytes = encrypted_contentinfo['encrypted_content'].native

        # after
        encrypted_content_field_index = encrypted_contentinfo._field_map['encrypted_content']
        (_, _, _, _, encrypted_trailer, *_) = encrypted_contentinfo.children[encrypted_content_field_index]
        if not encrypted_trailer:
            encrypted_content_bytes = encrypted_contentinfo['encrypted_content'].native
        else:
            read = 0
            encrypted_content_bytes = b''
            while read < len(encrypted_trailer):
                value, read = core._parse_build(encrypted_trailer, read)
                encrypted_content_bytes += value.native
```

**Comment by FilippVolodin** [comment]
I gave the wrong link. Here is exactly the same problem https://github.com/wbond/asn1crypto/issues/264
